### ISSUE TITLE
Allow prettier configuration to be set in non-npm projects

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/prettier-skill#112]
Since it is valid to have a `.prettierrc.json` and `.prettierignore` in a non-npm project, support updating just those files when a project has no package.json.

**Comment by ddgenome** [comment]
This may require the skill have the prettier executable available to it without installing in the project.

**Comment by cdupuis** [comment]
@ddgenome this skill should already run on non-npm projects as per https://github.com/atomist-skills/prettier-skill/blob/main/lib/events/lintOnPush.ts#L277. Is that not working?

**Comment by ddgenome** [comment]
The latter, the `.prettierrc.json` and `.prettierignore` will not be committed to the repo if it does not contain a package.json.

https://github.com/atomist-skills/prettier-skill/blob/c8ff6f645131fc9127f2c1a7b380f20a994a19f3/lib/events/updateToolsOnPush.ts#L96-L98
