### ISSUE TITLE
.prettierignore edit loop

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist-skills/prettier-skill#118]
My prettier skill is fighting over .prettierignore.  My .prettierignore file starts with a blank line.  Then prettier adds two rules and removes the blank line:

```
CHANGELOG.md
/doc/
```

Then a PR gets raised to add a blank line.  When I merge that, the two rules get deleted in another commit and a blank line is added.  Then another PR gets raised to remove the blank line.  I've merged the PR quite a few times, but I can't get the project into a state where it's happy with .pretterignore.  I don't actually have a CHANGELOG.md or doc directory in this project if that helps.

**Comment by cdupuis** [comment]
The .prettierignore is managed by the prettier-skill. You can't or rather shouldn't manually edit its content. 

If you need to manually edit the file, you should remove the repo from the skill's repo filter. 

Or we need some other marker in the repo that you want to manually edit the ignore file.

**Comment by slimslenderslacks** [comment]
I actually haven't manually edited it.  I'm just merging PRs that get made for me, and then atomist-bot is making Commits.  I'm probably not doing a good job explaining it but you can take a look at this public repo https://github.com/slimslender/clj-test-lib/commits/master.

**Comment by cdupuis** [comment]
Ah, let me review that commit chain. Thanks.

**Comment by cdupuis** [comment]
Turns out the skill was configured in two different workspace with two different configurations on the same repository. While this isn't a good UX, it certainly isn't something we can address at this point.
