### ISSUE TITLE
Preserve spacing in package.json when updating dependencies

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/prettier-skill#72]
When updating dependencies, spacing in the package.json and package-lock.json files should be preserved, similar to how `npm` does it.

**Comment by cdupuis** [comment]
Dependencies are always installed using the appropriate `npm install` commands. So that's not what is messing up the formatting. I've updated the code to preserve spacing like `npm` when manually updating the `package.json` to add scripts etc.
